<?xml version="1.0" ?>
<robot name="teststand"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
  <xacro:property name="base_w" value=".1" />
  <xacro:property name="base_l" value=".2" />
  <xacro:property name="base_h" value=".1" />
  <xacro:property name="base_m" value="0.485" />

  <xacro:include filename="leg.xacro" />

  <link name="root" />

   <joint name="joint_z" type="prismatic">
    <parent link="root"/>
    <child link="base_link"/>
    <limit effort="1000" lower="-10" upper="10" velocity="1000"/>
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <link name="base_link">
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 ${base_h/2.}"/>
        <mass value="${base_m}"/>
        <inertia ixx="${1./12. * base_m * (base_h*base_h + base_w*base_w)}"
                 iyy="${1./12. * base_m * (base_h*base_h + base_l*base_l)}"
                 izz="${1./12. * base_m * (base_w*base_w + base_l*base_l)}"
                 ixy="0" ixz="0" iyz="0"
        />
    </inertial>
    <visual>
        <origin rpy="0 0 0" xyz="0 0 ${base_h/2.}"/>
        <geometry>
          <mesh filename="package://robot_properties_teststand/meshes/cube.obj" scale="${base_l} ${base_w} ${base_h}"/>
        </geometry>
        <material name="white">
            <color rgba="1 1 1 1"/>
        </material>
    </visual>
    <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <box size="${base_l} ${base_w} ${base_h}"/>
        </geometry>
    </collision>
  </link>

  <xacro:leg prefix="" ry="0." rx="0."/>
</robot>
